# Generated by Django 6.0.2 on 2026-02-15 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0)),
                ('mode', models.CharField(choices=[('camera_on', 'Camera On'), ('camera_off', 'Camera Off')], default='camera_off', max_length=20)),
                ('focus_score_final', models.FloatField(blank=True, null=True)),
                ('time_idle', models.FloatField(default=0)),
                ('time_tab_hidden', models.FloatField(default=0)),
                ('time_face_missing', models.FloatField(default=0)),
                ('time_looking_away', models.FloatField(default=0)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('tag', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='SessionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('focus_score', models.FloatField()),
                ('is_tab_hidden', models.BooleanField(default=False)),
                ('is_idle', models.BooleanField(default=False)),
                ('is_face_missing', models.BooleanField(default=False)),
                ('is_looking_away', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.focussession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
