# Generated by Django 5.1.5 on 2026-03-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_focussession_sessionevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionevent',
            name='activity_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionevent',
            name='click_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionevent',
            name='distraction_burst_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionevent',
            name='ear_left',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionevent',
            name='ear_right',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionevent',
            name='face_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionevent',
            name='focus_ema_30s',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionevent',
            name='focus_ema_5min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionevent',
            name='focus_trend',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionevent',
            name='gaze_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionevent',
            name='gaze_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionevent',
            name='head_pitch',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionevent',
            name='head_roll',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionevent',
            name='head_yaw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionevent',
            name='idle_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionevent',
            name='keystroke_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionevent',
            name='mouse_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionevent',
            name='mouse_velocity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionevent',
            name='scroll_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionevent',
            name='session_elapsed_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionevent',
            name='tab_switch_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionevent',
            name='time_since_tab_return',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionevent',
            name='window_blur_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
