# Generated by Django 5.1.5 on 2026-03-29 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sessionevent_activity_level_sessionevent_click_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('report_type', models.CharField(choices=[('esm', 'Experience Sampling'), ('post_session', 'Post-Session')], max_length=20)),
                ('score', models.IntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_reports', to='api.focussession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
