# Generated by Django 5.1.5 on 2026-04-10 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_selfreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionevent',
            name='brow_down_left',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionevent',
            name='brow_down_right',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionevent',
            name='brow_inner_up',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionevent',
            name='eye_squint_left',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionevent',
            name='eye_squint_right',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionevent',
            name='eye_wide_left',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionevent',
            name='eye_wide_right',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionevent',
            name='jaw_open',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionevent',
            name='mouth_frown_left',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionevent',
            name='mouth_frown_right',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionevent',
            name='mouth_smile_left',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionevent',
            name='mouth_smile_right',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
