# Generated by Django 5.1.5 on 2026-04-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_sessionevent_brow_down_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='focussession',
            name='time_phone_use',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sessionevent',
            name='is_phone_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionevent',
            name='phone_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='focussession',
            name='duration',
            field=models.IntegerField(default=0, help_text='Duration in seconds.'),
        ),
        migrations.AlterField(
            model_name='focussession',
            name='mode',
            field=models.CharField(choices=[('camera_on', 'Camera On'), ('camera_off', 'Camera Off')], default='camera_off', help_text='Whether camera-based features are included.', max_length=20),
        ),
    ]
